services:
  app:
    container_name: ia_engineer_path
    working_dir: /src
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./:/src
    depends_on:
      - db
  db:
      container_name: ai_engineer_path_db
      image: pgvector/pgvector:pg13
      ports:
        - "5434:5432"  # Change the host port to 5433
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ai_engineer_path_postgres_data:/var/lib/postgresql/data/  # Change the volume name
volumes:
  ai_engineer_path_postgres_data:  # Define the new volume

    